/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Unauthenticated liveness + database check (Railway's health check).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Patients */
        get: operations["list_patients_patients_get"];
        put?: never;
        /** Create Patient */
        post: operations["create_patient_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient */
        get: operations["get_patient_patients__patient_id__get"];
        /** Update Patient */
        put: operations["update_patient_patients__patient_id__put"];
        post?: never;
        /**
         * Delete Patient
         * @description Soft delete: sets deleted_at. The record stays in the database but no
         *     longer appears in lookups (use ?include_deleted=true to list it).
         */
        delete: operations["delete_patient_patients__patient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calls */
        get: operations["list_calls_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Call */
        get: operations["get_call_calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Appointments */
        get: operations["list_appointments_appointments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Logs
         * @description Log records, newest first. Kept for 90 days.
         */
        get: operations["list_logs_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Log Events
         * @description Every event name that has been logged, for filtering.
         */
        get: operations["list_log_events_logs_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Headline counts for the dashboard homepage.
         */
        get: operations["get_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retell/tools/check-existing-patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Existing Patient */
        post: operations["check_existing_patient_retell_tools_check_existing_patient_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retell/tools/create-patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Patient */
        post: operations["create_patient_retell_tools_create_patient_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retell/tools/verify-patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Patient */
        post: operations["verify_patient_retell_tools_verify_patient_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retell/tools/get-patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Patient */
        post: operations["get_patient_retell_tools_get_patient_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retell/tools/update-patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Patient */
        post: operations["update_patient_retell_tools_update_patient_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retell/tools/get-appointment-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Appointment Slots */
        post: operations["get_appointment_slots_retell_tools_get_appointment_slots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retell/tools/book-appointment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book Appointment */
        post: operations["book_appointment_retell_tools_book_appointment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retell/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retell Webhook Probe
         * @description Retell's dashboard 'Test' / connectivity check may GET this URL before
         *     ever sending a real event. No signature required for a plain reachability
         *     check with no payload.
         */
        get: operations["retell_webhook_probe_retell_webhook_get"];
        put?: never;
        /** Retell Webhook */
        post: operations["retell_webhook_retell_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** AppointmentOut */
        AppointmentOut: {
            /** Appointment Id */
            appointment_id: string;
            /** Patient Id */
            patient_id: string;
            /** Slot Id */
            slot_id: string;
            /** Provider */
            provider: string;
            /** Spoken */
            spoken: string;
            /** Visit Type */
            visit_type: string;
            /** Status */
            status: string;
            /** Booked Via Call Id */
            booked_via_call_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CallOut */
        CallOut: {
            /** Call Id */
            call_id: string;
            /** From Number */
            from_number?: string | null;
            /** To Number */
            to_number?: string | null;
            /** Direction */
            direction?: string | null;
            /** Status */
            status?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Disconnection Reason */
            disconnection_reason?: string | null;
            /** Transcript */
            transcript?: string | null;
            /** Recording Url */
            recording_url?: string | null;
            /** Call Analysis */
            call_analysis?: {
                [key: string]: unknown;
            } | null;
            /**
             * Verified Patient Id
             * @description patient_id this call verified as, if any.
             */
            verified_patient_id?: string | null;
            /** Verified At */
            verified_at?: string | null;
            /**
             * Verification Attempts
             * @default 0
             */
            verification_attempts: number;
            /**
             * Patients Created
             * @description patient_ids registered during this call.
             */
            patients_created?: string[];
        };
        /** Envelope[CallOut] */
        Envelope_CallOut_: {
            data?: components["schemas"]["CallOut"] | null;
            error?: components["schemas"]["ApiError"] | null;
        };
        /** Envelope[PatientOut] */
        Envelope_PatientOut_: {
            data?: components["schemas"]["PatientOut"] | null;
            error?: components["schemas"]["ApiError"] | null;
        };
        /** Envelope[StatsOut] */
        Envelope_StatsOut_: {
            data?: components["schemas"]["StatsOut"] | null;
            error?: components["schemas"]["ApiError"] | null;
        };
        /** Envelope[list[str]] */
        Envelope_list_str__: {
            /** Data */
            data?: string[] | null;
            error?: components["schemas"]["ApiError"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListEnvelope[AppointmentOut] */
        ListEnvelope_AppointmentOut_: {
            /** Data */
            data: components["schemas"]["AppointmentOut"][];
            error?: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ListMeta"];
        };
        /** ListEnvelope[CallOut] */
        ListEnvelope_CallOut_: {
            /** Data */
            data: components["schemas"]["CallOut"][];
            error?: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ListMeta"];
        };
        /** ListEnvelope[LogOut] */
        ListEnvelope_LogOut_: {
            /** Data */
            data: components["schemas"]["LogOut"][];
            error?: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ListMeta"];
        };
        /** ListEnvelope[PatientOut] */
        ListEnvelope_PatientOut_: {
            /** Data */
            data: components["schemas"]["PatientOut"][];
            error?: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ListMeta"];
        };
        /** ListMeta */
        ListMeta: {
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** LogOut */
        LogOut: {
            /** Id */
            id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Level */
            level: string;
            /** Logger */
            logger: string;
            /**
             * Event
             * @description Set for EventLogger records; plain logging has message.
             */
            event?: string | null;
            /** Message */
            message?: string | null;
            /** Fields */
            fields?: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id?: string | null;
            /** Environment */
            environment?: string | null;
            /** Func */
            func?: string | null;
            /** Line */
            line?: number | null;
            /** Exception */
            exception?: string | null;
        };
        /** PatientCreate */
        PatientCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Date Of Birth
             * @description MM/DD/YYYY or YYYY-MM-DD; stored as YYYY-MM-DD.
             */
            date_of_birth: string;
            /**
             * Sex
             * @description Male, Female, Other, or Decline to Answer.
             */
            sex: string;
            /**
             * Phone Number
             * @description U.S. 10-digit number; stored as digits only.
             */
            phone_number: string;
            /** Email */
            email?: string | null;
            /** Address Line 1 */
            address_line_1: string;
            /** Address Line 2 */
            address_line_2?: string | null;
            /** City */
            city: string;
            /**
             * State
             * @description 2-letter code or full state name.
             */
            state: string;
            /** Zip Code */
            zip_code: string;
            /** Insurance Provider */
            insurance_provider?: string | null;
            /** Insurance Member Id */
            insurance_member_id?: string | null;
            /**
             * Preferred Language
             * @description Defaults to English.
             */
            preferred_language?: string | null;
            /** Emergency Contact Name */
            emergency_contact_name?: string | null;
            /** Emergency Contact Phone */
            emergency_contact_phone?: string | null;
        };
        /**
         * PatientOut
         * @description REST API shape: every field from the spec plus audit metadata, minus
         *     internal DB mechanics (Mongo _id, idempotency key).
         */
        PatientOut: {
            /**
             * Patient Id
             * @description UUID; the REST resource identifier.
             */
            patient_id: string;
            /**
             * Member Id
             * @description 8-digit ID read to the caller and used for phone verification.
             */
            member_id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Date Of Birth
             * @description YYYY-MM-DD.
             */
            date_of_birth: string;
            /** Sex */
            sex: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email?: string | null;
            /** Address Line 1 */
            address_line_1: string;
            /** Address Line 2 */
            address_line_2?: string | null;
            /** City */
            city: string;
            /** State */
            state: string;
            /** Zip Code */
            zip_code: string;
            /** Insurance Provider */
            insurance_provider?: string | null;
            /** Insurance Member Id */
            insurance_member_id?: string | null;
            /**
             * Preferred Language
             * @default English
             */
            preferred_language: string;
            /** Emergency Contact Name */
            emergency_contact_name?: string | null;
            /** Emergency Contact Phone */
            emergency_contact_phone?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Created Via
             * @description voice, api, or seed.
             */
            created_via?: string | null;
            /** Created Via Call Id */
            created_via_call_id?: string | null;
            /** Update History */
            update_history?: components["schemas"]["UpdateHistoryEntry"][];
        };
        /**
         * PatientUpdate
         * @description Partial update: only the fields present in the request are changed.
         *     Sending null clears an optional field; required fields can't be cleared.
         */
        PatientUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /**
             * Date Of Birth
             * @description MM/DD/YYYY or YYYY-MM-DD; stored as YYYY-MM-DD.
             */
            date_of_birth?: string | null;
            /**
             * Sex
             * @description Male, Female, Other, or Decline to Answer.
             */
            sex?: string | null;
            /**
             * Phone Number
             * @description U.S. 10-digit number; stored as digits only.
             */
            phone_number?: string | null;
            /** Email */
            email?: string | null;
            /** Address Line 1 */
            address_line_1?: string | null;
            /** Address Line 2 */
            address_line_2?: string | null;
            /** City */
            city?: string | null;
            /**
             * State
             * @description 2-letter code or full state name.
             */
            state?: string | null;
            /** Zip Code */
            zip_code?: string | null;
            /** Insurance Provider */
            insurance_provider?: string | null;
            /** Insurance Member Id */
            insurance_member_id?: string | null;
            /** Preferred Language */
            preferred_language?: string | null;
            /** Emergency Contact Name */
            emergency_contact_name?: string | null;
            /** Emergency Contact Phone */
            emergency_contact_phone?: string | null;
        };
        /** RetellCall */
        RetellCall: {
            /** Call Id */
            call_id: string;
            /** From Number */
            from_number?: string | null;
            /** To Number */
            to_number?: string | null;
            /** Direction */
            direction?: string | null;
            /** Transcript */
            transcript?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RetellToolRequest */
        RetellToolRequest: {
            /** Name */
            name: string;
            call: components["schemas"]["RetellCall"];
            /** Args */
            args?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** StatsOut */
        StatsOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Live Calls
             * @description Calls in progress: status ongoing and started within the last hour (Retell's default maximum call length), so a call whose call_ended webhook never arrived stops counting.
             */
            live_calls: number;
            /** Calls 24H */
            calls_24h: number;
            /**
             * Avg Call Duration Ms 24H
             * @description Across ended calls started in the last 24h.
             */
            avg_call_duration_ms_24h?: number | null;
            /** Calls Total */
            calls_total: number;
            /**
             * Patients Total
             * @description Active (not deleted) patients.
             */
            patients_total: number;
            /** Patients 24H */
            patients_24h: number;
            /**
             * Errors 24H
             * @description ERROR and CRITICAL log records.
             */
            errors_24h: number;
            /** Warnings 24H */
            warnings_24h: number;
        };
        /** UpdateHistoryEntry */
        UpdateHistoryEntry: {
            /**
             * Source
             * @default voice
             */
            source: string;
            /** Call Id */
            call_id?: string | null;
            /** Fields Changed */
            fields_changed: string[];
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_patients_patients_get: {
        parameters: {
            query?: {
                /** @description Exact, case-insensitive. */
                last_name?: string | null;
                /** @description MM/DD/YYYY or YYYY-MM-DD. */
                date_of_birth?: string | null;
                /** @description Any common U.S. format. */
                phone_number?: string | null;
                member_id?: string | null;
                include_deleted?: boolean;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_PatientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_patients_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PatientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PatientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_patient_patients__patient_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PatientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_patient_patients__patient_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                patient_id: string;
            };
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PatientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calls_calls_get: {
        parameters: {
            query?: {
                /** @description Only calls that registered or verified this patient. */
                patient_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_CallOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                call_id: string;
            };
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CallOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appointments_appointments_get: {
        parameters: {
            query?: {
                patient_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_AppointmentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_logs_logs_get: {
        parameters: {
            query?: {
                /** @description Only records at or after this time. */
                since?: string | null;
                /** @description Only records before this time. */
                until?: string | null;
                /** @description Minimum level. */
                level?: ("DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL") | null;
                event?: string | null;
                /** @description Leave out the per-request http_request records. */
                hide_http?: boolean;
                call_id?: string | null;
                request_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_LogOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_log_events_logs_events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_str__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_stats_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: {
                api_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StatsOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_existing_patient_retell_tools_check_existing_patient_post: {
        parameters: {
            query?: never;
            header?: {
                "x-retell-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetellToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_retell_tools_create_patient_post: {
        parameters: {
            query?: never;
            header?: {
                "x-retell-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetellToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_patient_retell_tools_verify_patient_post: {
        parameters: {
            query?: never;
            header?: {
                "x-retell-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetellToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_retell_tools_get_patient_post: {
        parameters: {
            query?: never;
            header?: {
                "x-retell-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetellToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_patient_retell_tools_update_patient_post: {
        parameters: {
            query?: never;
            header?: {
                "x-retell-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetellToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_appointment_slots_retell_tools_get_appointment_slots_post: {
        parameters: {
            query?: never;
            header?: {
                "x-retell-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetellToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_appointment_retell_tools_book_appointment_post: {
        parameters: {
            query?: never;
            header?: {
                "x-retell-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetellToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retell_webhook_probe_retell_webhook_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    retell_webhook_retell_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "x-retell-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
